name: iOS Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load JSON variables
        id: vars
        run: |
          echo "version=$(jq -r '.version' td-version.json)" >> $GITHUB_ENV
          echo "commit_hash=$(jq -r '.commit_hash' td-version.json)" >> $GITHUB_ENV

      - name: Run iOS Build Script
        run: bash scripts/ios/build.sh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ios-${{ env.version }}-${{ env.commit_hash }}
          name: iOS ${{ env.version }}-${{ env.commit_hash }}
          body: https://github.com/tdlib/td/tree/${{ env.commit_hash }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'td/tdjson.xcframework.zip'
          allowUpdates: true
